name: Package versions retention
on: [ release ]

permissions:
  packages: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'common-ui'
          package-type: 'npm'
          token: ${{ secrets.PAT }}
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true
