name: Package maintenance
on: [ push, release ]

permissions:
  packages: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: '@mlyngvo/common-ui'
          package-type: 'npm'
          token: ${{ secrets.GITHUB_PAT }}
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true
